version: '2'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - /Users/pederwaern/Docker/localdocker:/counter_app
    links:
      - db:mysql
    container_name: counterapp_web1
    depends_on:
      - db

  db:
    image: mysql:5.7
    restart: always
    container_name: counterapp_db_1
    environment:
      - MYSQL_ROOT_PASSWORD=rootpass
      - MYSQL_DATABASE=counter
